### ISSUE TITLE
Bloom issue

### ISSUE THREAD

**Issue by johnvibar** [johnvibar/ramen-shop#1]
I have added bloom effect but it is not working properly.

const renderScene = new RenderPass(scene, camera);

    // Configurable parameters: (resolution, strength, radius, threshold)
    const bloomPass = new UnrealBloomPass(new THREE.Vector2(window.innerWidth, window.innerHeight), 0.3, 0, 0.95);

    composer = new EffectComposer(renderer);
    
    const outputPass = new OutputPass( THREE.ReinhardToneMapping );
    // outputPass.toneMappingExposure = Math.pow( 1, 4.0 );

    composer.addPass(renderScene);
    composer.addPass(bloomPass);
    composer.addPass(outputPass);

Thanks

**Comment by pioneer830** [comment]
Hey John, Can you add SMAAPass effect for it?

**Comment by johnvibar** [comment]
Hey Pioneer, Thanks for your reply.
Could you share more detail plz?
Thanks

**Comment by pioneer830** [comment]
Like this:
const pass = new SMAAPass(window.innerWidth * renderer.getPixelRatio(), window.innerHeight * renderer.getPixelRatio());
    composer.addPass(pass);

**Comment by johnvibar** [comment]
Good, perfect!
Thanks
